#!/bin/bash
# Build "~/Desktop/Music3 Studio.app" — a thin launcher bundle. The code stays in
# ~/Projects/music3-studio, so editing app_qt.py needs no rebundling.
#
#   bash packaging/make_app_qt.sh
#
# Same recipe as Verdict Studio Qt: probe for the python3.13 that has PySide6 (Finder's PATH
# is /usr/bin:/bin), copy the framework's Python.app GUI stub into the bundle so the menu bar
# shows our name, exec it.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT="$(dirname "$HERE")"
APP="$HOME/Desktop/Music3 Studio.app"
ICNS="$HERE/Music3Studio.icns"
PY313="/opt/homebrew/opt/python@3.13/bin/python3.13"

[ -f "$ICNS" ] || "$PY313" "$HERE/make_icon.py"

case "$APP" in
  *.app) [ -d "$APP" ] && rm -rf "$APP" ;;
  *) echo "refusing to remove non-.app path: $APP" >&2; exit 1 ;;
esac
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"
cp "$ICNS" "$APP/Contents/Resources/Music3Studio.icns"

cat > "$APP/Contents/Info.plist" <<'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>en</string>
	<key>CFBundleDisplayName</key>
	<string>Music3 Studio</string>
	<key>CFBundleExecutable</key>
	<string>Music3Studio</string>
	<key>CFBundleIconFile</key>
	<string>Music3Studio</string>
	<key>CFBundleIdentifier</key>
	<string>com.nexuspivot.music3-studio</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>Music3 Studio</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>1.0</string>
	<key>CFBundleVersion</key>
	<string>1.0</string>
	<key>LSMinimumSystemVersion</key>
	<string>14.0</string>
	<key>NSHighResolutionCapable</key>
	<true/>
	<key>NSPrincipalClass</key>
	<string>NSApplication</string>
</dict>
</plist>
PLIST

LAUNCHER="$APP/Contents/MacOS/Music3Studio"
cat > "$LAUNCHER" <<LAUNCH
#!/bin/bash
# Music3 Studio launcher — generated by packaging/make_app_qt.sh, do not edit here.
# Reproduce a Finder launch with:
#   env -i PATH=/usr/bin:/bin:/usr/sbin:/sbin HOME="\$HOME" \\
#       "\$HOME/Desktop/Music3 Studio.app/Contents/MacOS/Music3Studio"
# M3_PREPARE=1 only resolves the interpreter and stub, then exits.
set -u

DIR="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
APP_PY="$PROJECT/app_qt.py"
BIN="\$DIR/Music3StudioPy"

export PATH="/opt/homebrew/bin:/usr/local/bin:\$HOME/.local/bin:\$PATH"

die() {
    osascript -e "display alert \"Music3 Studio\" message \"\$1\" as critical" >/dev/null 2>&1
    echo "Music3 Studio: \$1" >&2
    exit 1
}

PYTHON=""
for cand in \\
    $PY313 \\
    /opt/homebrew/bin/python3.13 \\
    "\$(command -v python3.13 || true)" \\
    "\$(command -v python3 || true)"; do
    if [ -n "\$cand" ] && [ -x "\$cand" ] && "\$cand" -c "from PySide6.QtWidgets import QApplication" >/dev/null 2>&1; then
        PYTHON="\$cand"
        break
    fi
done
[ -n "\$PYTHON" ] || die "No Python with PySide6 was found. Install python@3.13 and PySide6."

PREFIX="\$("\$PYTHON" -c 'import sys; print(sys.prefix)')"
GUISTUB="\$PREFIX/Resources/Python.app/Contents/MacOS/Python"

RUNNER=""
if [ -f "\$GUISTUB" ]; then
    if [ ! -f "\$BIN" ] || [ "\$GUISTUB" -nt "\$BIN" ]; then
        cp -f "\$GUISTUB" "\$BIN" 2>/dev/null && chmod +x "\$BIN" 2>/dev/null || true
    fi
    if [ -x "\$BIN" ]; then
        if ! "\$BIN" -c "import sys" >/dev/null 2>&1; then
            export PYTHONHOME="\$PREFIX"
        fi
        RUNNER="\$BIN"
    fi
fi
[ -n "\$RUNNER" ] || RUNNER="\$PYTHON"

if [ "\${M3_PREPARE:-}" = "1" ]; then
    echo "python=\$PYTHON"
    echo "runner=\$RUNNER"
    exit 0
fi

[ -f "\$APP_PY" ] || die "Missing \$APP_PY. The .app is only a launcher; the code lives in $PROJECT."

exec "\$RUNNER" "\$APP_PY"
LAUNCH
chmod +x "$LAUNCHER"

M3_PREPARE=1 "$LAUNCHER"

plutil -lint "$APP/Contents/Info.plist"
xattr -cr "$APP"
codesign --force --deep -s - "$APP"
codesign --verify --verbose "$APP"
echo "built $APP"
